{
 "title": "LLM dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Gateway metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency gateway",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job=\"simple-ai-gateway\", handler=\"/v1/chat/completions\"}[5m]))",
       "legendFormat": "{{job}}-0.95"
      },
      {
       "expr": "histogram_quantile(0.99, rate(http_request_duration_seconds_bucket{job=\"simple-ai-gateway\", handler=\"/v1/chat/completions\"}[5m]))",
       "legendFormat": "{{job}}-0.99"
      },
      {
       "expr": "histogram_quantile(0.5, rate(http_request_duration_seconds_bucket{job=\"simple-ai-gateway\", handler=\"/v1/chat/completions\"}[5m]))",
       "legendFormat": "{{job}}-0.5"
      }
     ]
    },
    {
     "title": "Successful requests total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "http_requests_total{status=\"2xx\", handler=\"/v1/chat/completions\", job=\"simple-ai-gateway\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Total requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "rate(http_requests_total{handler=\"/v1/chat/completions\"}[5m])",
       "legendFormat": "2xx requests"
      }
     ]
    },
    {
     "title": "Gateway Rate limits",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "rate(http_requests_total{status=\"429\"}[1m]) OR vector(0)",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "VLLM latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "End to end latency in vllm",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, rate(vllm:e2e_request_latency_seconds_bucket[5m]))",
       "legendFormat": "{{model_name}}-0.5"
      },
      {
       "expr": "histogram_quantile(0.95, rate(vllm:e2e_request_latency_seconds_bucket[5m]))",
       "legendFormat": "{{model_name}}-0.95"
      },
      {
       "expr": "histogram_quantile(0.99, rate(vllm:e2e_request_latency_seconds_bucket[5m]))",
       "legendFormat": "{{model_name}}-0.99"
      }
     ]
    },
    {
     "title": "Time to first token",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, rate(vllm:time_to_first_token_seconds_bucket[5m]))",
       "legendFormat": "{{model_name}}-0.95"
      },
      {
       "expr": "histogram_quantile(0.99, rate(vllm:time_to_first_token_seconds_bucket[5m]))",
       "legendFormat": "{{model_name}}-0.99"
      },
      {
       "expr": "histogram_quantile(0.5, rate(vllm:time_to_first_token_seconds_bucket[5m]))",
       "legendFormat": "{{model_name}}-0.5"
      }
     ]
    },
    {
     "title": "Inter token latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(vllm:inter_token_latency_seconds_bucket[5m]))",
       "legendFormat": "{{model_name}}-0.99"
      },
      {
       "expr": "histogram_quantile(0.95, rate(vllm:inter_token_latency_seconds_bucket[5m]))",
       "legendFormat": "{{model_name}}-0.95"
      },
      {
       "expr": "histogram_quantile(0.5, rate(vllm:inter_token_latency_seconds_bucket[5m]))",
       "legendFormat": "{{model_name}}-0.5"
      }
     ]
    }
   ]
  },
  {
   "title": "VLLM throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "prompt tokens recomputation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "rate(vllm:prompt_tokens_recomputed_total[1m])",
       "legendFormat": "{{model_name}}"
      }
     ]
    },
    {
     "title": "Total tokens generated",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "targets": [
      { "expr": "vllm:generation_tokens_total", "legendFormat": "{{model_name}}-total" }
     ]
    }
   ]
  }
 ]
}